name: ci

on:
  pull_request:
    branches:
      - 'main'

jobs:
  docker-node-14-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: firebase-toos:latest-node-14
          file: Dockerfile.node14
